import type { Metadata } from "next";
import Aside from "@/components/Aside";
import { checkAuth, getUserAuth } from "@/lib/auth/utils";
import { redirect } from "next/navigation";
import { ModeToggle } from "@/components/ui/ThemeToggle";
import { UserButton } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  await checkAuth();
  const { session } = await getUserAuth();

  if (!session || session.user.role !== "admin") return redirect("/");

  return (
    <div className="flex">
      <Aside />
      <main className="flex-grow p-3">
        <div className="flex justify-end mb-4">
          <div className="flex items-center gap-2">
            <ModeToggle />
            <UserButton afterSignOutUrl="/" />
          </div>
        </div>
        {children}
      </main>
    </div>
  );
}
