import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { checkAuth } from "@/lib/auth/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  await checkAuth();

  return (
    <div className="flex flex-col w-full h-[100vh]">
      <Navbar />
      <div className="max-w-4xl min-w-[869px] mx-auto md:p-0 p-6 my-8 flex-1">
        {children}
      </div>
      <footer className="bg-slate-800 text-white text-center py-8 w-full">
        Copyright © 2023. All rights reserved.
      </footer>
    </div>
  );
}
