import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { checkAuth } from "@/lib/auth/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  await checkAuth();

  return (
    <div className="max-w-3xl mx-auto md:p-0 p-6">
      <Navbar />
      {children}
    </div>
  );
}
